---
- name: install mongodb packages
  with_items: "{{ mongodb_packages }}"
  pkgng:
    name: "{{ item.name }}"
    state: present
  notify:
    - restart mongodb

- name: enable mongodb
  template:
    src: mongod.j2
    dest: /etc/rc.conf.d/mongod

- name: configure mongodb
  template:
    src: mongodb.conf.j2
    dest: /usr/local/etc/mongodb.conf
  notify:
    - restart mongodb
